name: Run Tests and Deploy Report

on:
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run WebdriverIO Tests
      run: npm test  # Ensure this runs your WebdriverIO tests and generates the Allure report

    - name: Deploy Allure Report
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'
        git checkout gh-pages
        cp -r allure-report/* .
        git add .
        git commit -m 'Update Allure report'
        git push origin gh-pages
