name: Run Tests and Deploy Allure Report

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Set this to your Node.js version if needed

      - name: Install dependencies
        run: npm install  # or yarn install if you use Yarn

      - name: Run Tests
        run: npm test  # This will use the "test" script defined in package.json

      - name: Generate Allure report
        run: npm run allure-report  # This will use the "allure-report" script defined in package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
