name: Run Tests and Deploy Allure Report

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Chrome
      run: sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: npm install

    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Print global npm binary path
      run: echo $(npm bin -g)

    - name: List global binaries
      run: ls -l $(npm bin -g)

    - name: Run tests and generate Allure report
      run: |
        npx wdio ./wdio.conf.js
        $(npm bin -g)/allure generate allure-results --clean -o allure-report

    - name: Check if Allure report was generated
      run: |
        if [ ! -d "allure-report" ]; then
          echo "Allure report directory does not exist."
          exit 1
        fi

    - name: Deploy Allure report to GitHub Pages
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git fetch origin gh-pages || git checkout -b gh-pages
        git reset --hard origin/gh-pages
        rm -rf *
        cp -r allure-report/* .
        git add .
        git commit -m "Update Allure report" || echo "No changes to commit"
        git push origin gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
