name: Generate and Deploy Allure Report

on:
  workflow_dispatch:  # Allows manual dispatch of this workflow
  repository_dispatch:  # Allows triggering via the API if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Add execute permissions for wdio
      run: chmod +x ./node_modules/.bin/wdio

    - name: Run WebdriverIO Tests
      run: npx wdio ./wdio.conf.js

    - name: Deploy Allure Report to gh-pages
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create a directory for the Allure report if it doesn't exist
        mkdir -p out
        
        # Copy the Allure report to the `out` directory
        cp -r allure-report/* out
        
        # Checkout the gh-pages branch
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        git reset --hard
        
        # Copy the new Allure report files into the gh-pages branch
        cp -r out/* .
        
        # Clean up
        rm -rf out
        
        # Add, commit, and push the Allure report to the gh-pages branch
        git add .
        git commit -m "Update Allure Report"
        git push origin gh-pages --force
