name: Run Tests and Deploy Report

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Add execute permissions for wdio
      run: chmod +x ./node_modules/.bin/wdio

    - name: Run WebdriverIO Tests
      run: npx wdio ./wdio.conf.js

    - name: Deploy Allure Report
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your.email@example.com'

        # Switch to gh-pages branch
        git fetch origin gh-pages || git checkout --orphan gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        git reset --hard

        # Store the new Allure report in a temporary directory
        mv allure-report ../allure-report-new

        # Clean the branch
        git rm -rf .

        # Move the new Allure report files back
        mv ../allure-report-new/* .

        git add .
        git commit -m 'Update Allure report'
        git push origin gh-pages --force
