name: Generate and Deploy Allure Report

on:
  workflow_dispatch:  # Allows manual dispatch of this workflow
  repository_dispatch:  # Allows triggering via the API if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies (e.g., WebdriverIO, Allure)
      - name: Install Dependencies
        run: |
          npm install

      # Run tests and generate Allure Report
      - name: Run Tests
        run: |
          npm run test  # Make sure this command generates the Allure report

      # Deploy Allure Report to gh-pages branch
      - name: Deploy Allure Report to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p out
          cp -r allure-report/* out
          git checkout gh-pages
          cp -r out/* .
          git add .
          git commit -m "Update Allure Report"
          git push origin gh-pages
