name: CI and Deploy Allure Report

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Check Allure Installation
      id: check_allure
      run: |
        if ! command -v allure &> /dev/null; then
          echo "Allure is not installed"
          echo "install=false" >> $GITHUB_ENV
        else
          echo "Allure is installed"
          echo "install=true" >> $GITHUB_ENV
        fi

    - name: Install Allure
      if: env.install == 'false'
      run: |
        ALLURE_VERSION=2.13.8
        curl -o allure.zip -L "https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}-zip.zip"
        unzip allure.zip -d $GITHUB_ENV
        echo "$GITHUB_ENV/allure/bin" >> $GITHUB_PATH

    - name: Set permissions for Allure
      if: env.install == 'false'
      run: chmod +x $GITHUB_ENV/allure/bin/allure

    - name: Fix permissions for WebdriverIO
      run: chmod +x ./node_modules/.bin/wdio

    - name: Run tests
      run: npm test

    - name: Generate Allure Report
      run: npm run allure-report

    - name: Deploy Allure Report to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: allure-report
        token: ${{ secrets.GITHUB_TOKEN }}
